<a href="https://colab.research.google.com/github/arturszaro/Data_Science_Bootcamp/blob/main/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [5]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1)


4.123105625617661

In [7]:
v2 = np.array([-10,10,13])

In [8]:
np.linalg.norm(v2)

19.209372712298546

In [9]:
p = np.array([3,0])
q = np.array([0,4])

In [10]:
np.linalg.norm(p-q)

5.0

In [11]:
p = np.array([3,0,1])
q = np.array([0,4,2])

In [12]:
np.linalg.norm(p-q)

5.0990195135927845

In [13]:
A = np.array([[2,4],[-1,3]])

In [14]:
np.linalg.det(A)

9.999999999999998

In [15]:
round(np.linalg.det(A))

10

In [16]:
np.trace(A)

5

In [17]:
np.eye(5,dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
A

array([[ 2,  4],
       [-1,  3]])

In [20]:
B = np.linalg.inv(A)

In [21]:
b

NameError: ignored

In [22]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [23]:
np.dot(A,B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [25]:
np.set_printoptions(precision=4, suppress = True)

In [27]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [28]:
c = np.array([[3,1,2],[5,6,7],[8,2,1]])

In [29]:
c

array([[3, 1, 2],
       [5, 6, 7],
       [8, 2, 1]])

In [30]:
np.linalg.det(c)

-48.99999999999999

In [31]:
8*7

56

In [32]:
48*2

96

In [33]:
18+20+56-96-42-5

-49

In [37]:
A = np.array([[2,4],[1,-1]])

In [38]:
A

array([[ 2,  4],
       [ 1, -1]])

In [39]:
B = np.array([[10],[-1]])

In [40]:
B

array([[10],
       [-1]])

In [41]:
A_inv = np.linalg.inv(A)

In [42]:
x =np.dot(A_inv, B)

In [43]:
x

array([[1.],
       [2.]])