<a href="https://colab.research.google.com/github/arturszaro/Data_Science_Bootcamp/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


### tekst


In [ ]:
print('siema')

siema


# Nowa sekcja

In [ ]:
clear()


In [ ]:
clear()

In [4]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy as np

In [6]:
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [10]:
x = np.array([1,3])

In [11]:
x

array([1, 3])

In [12]:
print(x)

[1 3]


In [13]:
type(x)

numpy.ndarray

In [14]:
x.ndin

AttributeError: ignored

In [15]:
x.ndir

AttributeError: ignored

In [16]:
x.ndim

1

In [17]:
x.shape

(2,)

In [18]:
x.size

2

In [19]:
x.dtype

dtype('int64')

In [21]:
x = np.array([1.3, 2.3,1.4])

In [22]:
print(x)

[1.3 2.3 1.4]


In [23]:
x.dtype

dtype('float64')

In [25]:
x = np.array([[1,2],[-3,1]])

In [26]:
x.shape

(2, 2)

In [29]:
x.ndim

2

In [30]:
x = np.array([[1,2,4],[4,2,1]])

In [31]:
print(x)

[[1 2 4]
 [4 2 1]]


In [32]:
x.shape

(2, 3)

In [39]:
x = np.array(
    [[[4,3,2],
      [3,1,2],
      [3,1,2]],
      
      [[4,1,3],
       [3,1,2],
       [4,2,1]],
     
     [[4,1,3],
      [3,1,2],
      [4,2,1]]]
)

In [40]:
x.shape

(3, 3, 3)

Typt danych

In [42]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [43]:
A = np.array([1,2,3], dtype="float")

In [44]:
a.dtype

dtype('int64')

In [45]:
A.dtype

dtype('float64')

In [46]:
a = np.array([1.0,2.1,3.5], dtype="int")
a.dtype

dtype('int64')

In [47]:
print(a)

[1 2 3]


In [48]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.dtype

numpy.dtype

In [51]:
np.ones(shape=(5,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
np.full(shape=(3,3),fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [53]:
np.arrange(10)

AttributeError: ignored

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [56]:
np.arange(start=10,stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [59]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [60]:
a = np.arange(15)

In [61]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
a.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
a = np.array([3,1,4,2])
b = np.array([3,-1,3,2])
print(a)
print(b)


[3 1 4 2]
[ 3 -1  3  2]


In [66]:
a+b

array([6, 0, 7, 4])

In [67]:
a*b


array([ 9, -1, 12,  4])

In [68]:
a/b

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [69]:
a+3


array([6, 4, 7, 5])

In [70]:
2 * a


array([6, 2, 8, 4])

In [71]:
a + 3*b

array([12, -2, 13,  8])

In [72]:
np.add(a,b)

array([6, 0, 7, 4])

In [74]:
np.subtract(a,b)

array([0, 2, 1, 0])

In [78]:
c = np.divide(a,b)

print(np.multiply(a,b))
print(c)


[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [80]:
x = np.array([[1,3],[-2,0]])
y = np.array([[6,0],[-1,2]])

In [81]:
x*y


array([[6, 0],
       [2, 0]])

In [82]:
print(x)

print(y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [83]:
np.dot(a,b)

24

In [84]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

In [85]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [86]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [87]:
x@y

array([[  3,   6],
       [-12,   0]])

In [97]:
np.random.seed(0)

In [93]:
np.random.randn(10,4)

array([[ 0.96939671, -1.17312341,  1.94362119, -0.41361898],
       [-0.74745481,  1.92294203,  1.48051479,  1.86755896],
       [ 0.90604466, -0.86122569,  1.91006495, -0.26800337],
       [ 0.8024564 ,  0.94725197, -0.15501009,  0.61407937],
       [ 0.92220667,  0.37642553, -1.09940079,  0.29823817],
       [ 1.3263859 , -0.69456786, -0.14963454, -0.43515355],
       [ 1.84926373,  0.67229476,  0.40746184, -0.76991607],
       [ 0.53924919, -0.67433266,  0.03183056, -0.63584608],
       [ 0.67643329,  0.57659082, -0.20829876,  0.39600671],
       [-1.09306151, -1.49125759,  0.4393917 ,  0.1666735 ]])

In [94]:
np.random.rand()

0.5356328030249583

In [95]:
np.random.rand(10,2)

array([[0.58990998, 0.73012203],
       [0.311945  , 0.39822106],
       [0.20984375, 0.18619301],
       [0.94437239, 0.7395508 ],
       [0.49045881, 0.22741463],
       [0.25435648, 0.05802916],
       [0.43441663, 0.31179588],
       [0.69634349, 0.37775184],
       [0.17960368, 0.02467873],
       [0.06724963, 0.67939277]])

In [102]:
np.random.randint(low=10,high=101, size=10)

array([19, 93, 31, 46, 97, 80, 98, 98, 22, 68])

In [103]:
random.randint(low=10,high=101)

NameError: ignored

In [104]:
np.random.choice(['python','choice'])

'choice'

In [105]:
data = np.arange(10)

In [106]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.random.shuffle(data)

In [108]:
data

array([5, 2, 3, 4, 1, 0, 9, 8, 7, 6])

In [109]:
np.exp(1)

2.718281828459045

In [110]:
np.exp(2)

7.38905609893065

In [111]:
np.sqrt(9)

3.0

In [113]:
np.all([2,3,0,1])

False

In [115]:
np.any([1,0,2,3])

True

In [116]:
bool(0)

False

In [117]:
bool(1)

True

In [119]:
a = np.random.rand(5)

In [120]:
a


array([0.52047748, 0.67887953, 0.72063265, 0.58201979, 0.53737323])

In [121]:
np.max(a)

0.7206326547259168

In [122]:
np.argmax(a)

2

In [124]:
a[np.argmin(a)]

0.5204774795512048

In [125]:
np.argsort(a)

array([0, 4, 3, 1, 2])

In [126]:
np.max(a)

0.7206326547259168

In [127]:
np.min(a)

0.5204774795512048

In [128]:
np.mean(a)

0.6078765371840399

In [129]:
mp.median(a)

NameError: ignored

In [130]:
np.median(a)

0.5820197920751071

In [131]:
np.std(a)

0.07878229495660821

In [132]:
a = np.arange(20)

In [133]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
a[2]

2

In [135]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [136]:
a[:2]

array([0, 1])

In [137]:
a[0:2]

array([0, 1])

In [138]:
a[-3]

17

In [139]:
a[-3:]

array([17, 18, 19])

In [141]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [142]:
a[0]

0

In [144]:
a[:,0]

IndexError: ignored

In [145]:
a = a.reshape(4,5)

In [146]:
a[0]

array([0, 1, 2, 3, 4])

In [147]:
a[:,0]

array([ 0,  5, 10, 15])

In [148]:
a[3][2]

17

In [149]:
a[3,2]

17

In [154]:
for row in a:
  print(row[0])

0
5
10
15


In [161]:
for row in a:
  print('\n')
  for collumn in range(len(a)+1):
    print(row[collumn])



0
1
2
3
4


5
6
7
8
9


10
11
12
13
14


15
16
17
18
19


In [162]:
print(a.flat)

In [163]:
a.shape

(4, 5)

In [164]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [165]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [166]:
a.t

AttributeError: ignored

In [167]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [168]:
a = np.arange(start=-10,stop=10, step =0.5)

In [169]:
a

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [170]:
a.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [171]:
a = a.reshape(10,-1)


In [172]:
a>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [173]:
a[a>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [174]:
a[a>3 and a<5]

ValueError: ignored

In [175]:
np.bitwise_and(a>-5, a<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [176]:
np.bitwise_or(a<-5,a>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])